[workspace]
authors = ["owndev"]
channels = ["conda-forge"]
name = "Open-WebUI-Functions"
platforms = ["linux-64"]

[tasks]
format = "ruff format"
lint = { cmd = "ruff check", depends-on = ["format"] }

[dependencies]
ruff = ">=0.11.10,<0.12"
