name: Report a bug
description: Report an issue that you encountered while using the project.
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for reporting a bug!**  
        Please complete the information below to help us reproduce and fix the issue.

  - type: input
    attributes:
      label: Bug title
      description: A brief summary of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: |
        What went wrong? Include:
        - What you expected to happen
        - What actually happened
        - Any error messages or screenshots
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Describe the steps we need to take to see the issue. Be as specific as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Provide relevant environment details:
        - OS, browser/device (if relevant)
        - Software version or commit hash
        - Any configuration or plugins used
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add links to logs, screenshots, or related issues if available.
    validations:
      required: false
